if(BUILD_SERVER_GUI_APP)
    if(NOT ADD_QT_LIB)
        message(FATAL_ERROR "BUILD_SERVER_GUI_APP=ON requires ADD_QT_LIB=ON for the current Qt-based GUI example")
    endif()
    set(SERVER_EXECUTABLE_SOURCE "${CMAKE_CURRENT_LIST_DIR}/../source/main/widget_main.cpp")
else()
    message(WARNING "BUILD_SERVER_GUI_APP=OFF but console_main.cpp is not available; falling back to widget_main.cpp")
    set(SERVER_EXECUTABLE_SOURCE "${CMAKE_CURRENT_LIST_DIR}/../source/main/widget_main.cpp")
endif()
