if(BUILD_GUI_APP)
    if(NOT ADD_QT_LIB)
        message(FATAL_ERROR "BUILD_GUI_APP=ON requires ADD_QT_LIB=ON for the current Qt-based GUI example")
    endif()
    set(CLIENT_EXECUTABLE_SOURCE "${CMAKE_SOURCE_DIR}/source/client/main/widget_main.cpp")
else()
    set(CLIENT_EXECUTABLE_SOURCE "${CMAKE_SOURCE_DIR}/source/client/main/console_main.cpp")
endif()

if(BUILD_GUI_APP)
    if(NOT ADD_QT_LIB)
        message(FATAL_ERROR "BUILD_GUI_APP=ON requires ADD_QT_LIB=ON for the current Qt-based GUI example")
    endif()
    set(SERVER_EXECUTABLE_SOURCE "${CMAKE_SOURCE_DIR}/source/server/main/widget_main.cpp")
else()
    set(SERVER_EXECUTABLE_SOURCE "${CMAKE_SOURCE_DIR}/source/server/main/console_main.cpp")
endif()
